name: Deploy to production
on: 
  push:
    branches:
      - production #here we choose to deploy only when a push is on production
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: www.visualum.com
    steps:
    - uses: actions/checkout@v1
    - uses: aasmal97/deploy-react-app-to-aws@v1.2.0
      with: 
        aws_region: ${{ secrets.AWS_APP_REGION }}
        aws_access_key_id: ${{ secrets.AWS_S3_DEPLOY_USER_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_S3_DEPLOY_USER_SECRET_KEY }}
        cloudfront_distribution_id: ${{ secrets.AWS_APP_DISTRIBUTION_ID }}
        bucket_name: ${{ secrets.AWS_APP_BUCKET_NAME }}
        react_app_secrets: ${{ toJson(secrets) }}
        node_verison: 16
        path_to_app: ./